from django.utils.text import slugify

from notes.models import Note

from .base_test import (
    BaseTestCase,
    URLS_INSTANCE,
    NOTE_DATA,
)


class TestAutoslug(BaseTestCase):
    def test_slug_autogenerated(self):
        """Slug заметки должен быть автоматически сгенерирован."""
        form_data = {
            'title': 'Comment',
            'text': 'text-text-text',
        }
        response = self.user_client.post(
            URLS_INSTANCE.add_note,
            data=form_data,
            follow=True
        )
        self.assertRedirects(response, URLS_INSTANCE.success)
        note = Note.objects.get(title=form_data['title'])
        expected_slug = slugify(form_data['title'])[:100]
        self.assertEqual(note.slug, expected_slug)

    def test_slug_is_unique(self):
        """Slug заметки должен быть уникальным."""
        initial_count = Note.objects.count()
        self.user_client.post(URLS_INSTANCE.add_note, data=NOTE_DATA)
        response = self.user_client.post(
            URLS_INSTANCE.add_note,
            data=NOTE_DATA,
            follow=True
        )
        self.assertFormError(
            response, 'form', 'slug',
            'sample_slug - такой slug уже существует, '
            'придумайте уникальное значение!'
        )
        self.assertEqual(Note.objects.count(), initial_count)
